### ISSUE TITLE
cern: `account_setup` not working

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-oauthclient#115]
For some reason [this](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/cern.py#L319)
```python
assert not isinstance(g.identity, AnonymousIdentity)
```
evaluates to `False`. (To investigate more in depth)

cc @pamfilos

**Comment by jirikuncar** [comment]
The default form validation stopped working: https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/utils.py#L117

**Comment by jirikuncar** [comment]
It looks like Flask-WTF>=0.14 has some issues with CSRF validation.

**Comment by switowski** [comment]
Latest version of `Flask-WTF` (0.14.2) seems to have this issue fixed (tested with @egabancho on `cdslabs-qa`), so we can close it.

**Comment by egabancho** [comment]
I think this issue is still valid, we didn't tested properly as the error only happens at **first** login.
Indeed the only version of Flask-WTF that seems to be working is `0.13.1`.

cc @pamfilos @ioannistsanaktsidis

**Comment by tobiasfrust** [comment]
I wanted to let you know, that I still experienced problems with CSRF validation in combination with the `invenio-userprofiles` module.
For the RegistrationForm which did not include `invenio-userprofiles` everything worked as expected. With invenio-userprofiles enabled, form validation stopped working again. (I used the [create_csrf_disabled_registrationform()](https://github.com/inveniosoftware/invenio-oauthclient/blob/4539c272ca10a11b2e3c8ff379eb98e830bb9eed/invenio_oauthclient/utils.py#L227-L235] )-function from `invenio-oauthclient`.)

The problem was, that in the subform created by `invenio-userprofiles` CSRF-validation was still active. After deleting the `csrf_token` in the subform and also setting csrf-validation to false, the form validation succeeded.

My current solution is to disable csrf-validation as follows for `Flask-WTF>=0.14` for a given form:

```python
def disable_csrf(form):
  form.meta.csrf = False
  if 'csrf_token' in form:
    del form.csrf_token
    for f in form:
      if isinstance(f, FormField):
        disable_csrf(f.form)
```

I wanted to let you know my experience just in case the same situation is valid for `invenio-oauthclient`.

**Comment by MiltiadisAlexis** [comment]
I tried to replicate the issue, using `Flask-WTF` (0.14.2) and `invenio-userprofiles`(1.0.0b1) and after testing it (with @ntarocco) , [create_csrf_disabled_registrationform()](https://github.com/inveniosoftware/invenio-oauthclient/blob/4539c272ca10a11b2e3c8ff379eb98e830bb9eed/invenio_oauthclient/utils.py#L227-L235%5D) seems to working as expected.

**Comment by lnielsen** [comment]
@tobiasfrust Can you check if you have all the latest releases of packages and see if you are still experiencing the issue. If you still have the issue, further information on exactly how to replicate it would help us a lot in trying to fix it for good.

**Comment by tobiasfrust** [comment]
I just tried to replicate the issue by providing some tests with `WTF_CSRF_ENABLED=True`. You can see my code changes in this [commit](https://github.com/tobiasfrust/invenio-oauthclient/commit/f46fae585d0f03a31e5d78ed099bcff62867f4cf).

I just ran the tests with Travis and you can see the result e.g. [here](https://travis-ci.org/tobiasfrust/invenio-oauthclient/jobs/289500336#L552-L573). As you can see, form validation fails with the currently used method. I also printed the form to the console, and there was a `csrf_token` in the userprofiles subform, which is the reason for failing validation I guess. 
The output of the print statements is shown [here](https://travis-ci.org/tobiasfrust/invenio-oauthclient/jobs/289510223#L671-L673).

In your [oauth_register](https://github.com/inveniosoftware/invenio-oauthclient/blob/4539c272ca10a11b2e3c8ff379eb98e830bb9eed/invenio_oauthclient/utils.py#L122)-function your call `form.validate()`. If I did not miss anything in my tests, the user registration should not succeed because of `form.validate()=False`. So, there should only be a problem on the very first sign-in.

I also added a second test, which uses an updated way of disabling csrf (https://github.com/tobiasfrust/invenio-oauthclient/blob/21c1189679ce4be89c5ed2dd7db2a53452aa385c/invenio_oauthclient/utils.py#L238-L268). With these changes, form validation succeeds.

If you need further information or if I missed anything, just let me know.

**Comment by MiltiadisAlexis** [comment]
@tobiasfrust Thank you for the information, we managed to reproduce the issue through the tests and will try to fix it.
