### ISSUE TITLE
test: build error on release builds

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauthclient#174]
https://travis-ci.org/inveniosoftware/invenio-oauthclient/jobs/378447672

**Comment by switowski** [comment]
In Flask 1.0, the exception type is changing from `ValueError` to `TypeError`:
`Flask.make_response() raises TypeError instead of ValueError for bad response types. The error messages have been improved to describe why the type is invalid. (#2256)`  - see the [CHANGELOG](http://flask.pocoo.org/docs/1.0/changelog/#version-1-0).

@lnielsen  - is it ok to bump the version of Flask to 1.0 (after I changed the exception type, tests are passing on Flask 1.0, so in my opinion we could do this)? Otherwise, I will have to pin the version of Flask to 0.12.
